kind: Service
apiVersion: v1
metadata:
  name: monolith
  labels:
    app: monolith
spec:
  ports:
    - name: http
      port: 443
      protocol: TCP
      targetPort: 443
      nodePort: 31000
  selector:
    app: monolith
    role: frontend-backend
    secure: enabled
    env: dev
  sessionAffinity: None
  type: LoadBalancer
